spring:
  application:
    name: D4 Auctioneer

feign:
  dtrade:
    api:
      url: "https://diablo.trade/api/items" # ?cursor=1&incense=Song%20of%20the%20Mountain&mode=season%20softcore&rune=Bac&sort=lowest&type=WTB
